<!--
/**
 * ╔╗╔╗╔╦══╦══╦══╦════╦═══╗╔══╦═══╦═══╗
 * ║║║║║╠═╗║╔═╩╗╔╩═╗╔═╣╔══╝║╔╗║╔═╗║╔══╝
 * ║║║║║╠═╝║╚═╗║║──║║─║╚══╗║║║║╚═╝║║╔═╗
 * ║║║║║╠═╗╠═╗║║║──║║─║╔══╝║║║║╔╗╔╣║╚╗║
 * ║╚╝╚╝╠═╝╠═╝╠╝╚╗─║║─║╚══╦╣╚╝║║║║║╚═╝║
 * ╚═╝╚═╩══╩══╩══╝─╚╝─╚═══╩╩══╩╝╚╝╚═══╝
 * 
 * Examples and documentation at the: http://w3site.org
 * 
 * @copyright   Copyright (c) 2015-2016 Tereta Alexander. (http://www.w3site.org)
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
-->
<div><?php echo $block->getTitle() ?></div>
<ul>
    <?php foreach($block->getItems() as $item) : ?>
        <li>
            <a href="<?php echo $item->dataItem->link ?>"><?php echo $item->dataItem->title ?></a>
            
            <?php $e= $this->getSubItems($item->dataTree) ?>
            <?php echo $this->getSubItems($item->dataTree)->toHtml() ?>
        </li>
    <?php endforeach ?>
</ul>